"""empty message

Revision ID: 13e4c38fd25a
Revises: 0d1fda979e71
Create Date: 2024-03-18 13:33:00.129422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '13e4c38fd25a'
down_revision: Union[str, None] = '0d1fda979e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_candidato', sa.Integer(), nullable=False),
    sa.Column('medio_comunicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    # ### end Alembic commands ###
