"""empty message

Revision ID: 49708acc5da0
Revises: 68832ec8c047
Create Date: 2024-05-24 20:43:23.986135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49708acc5da0'
down_revision: Union[str, None] = '68832ec8c047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ha_votado')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ha_votado', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
