"""empty message

Revision ID: 68832ec8c047
Revises: 
Create Date: 2024-05-24 20:18:29.988341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68832ec8c047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_cedula', sa.Integer(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ha_votado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_candidato', sa.Integer(), nullable=False),
    sa.Column('medio_comunicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votos')
    op.drop_table('user')
    # ### end Alembic commands ###
